### PR TITLE
Show aspects in tooltip

### LINKED ISSUE #22117: Thaumcraft Aspects not showing in NEI.
### Your GTNH Discord Username

StoneLegion

### Your Pack Version

2.8.1

### Your Server

StoneLegion

### Java Version

Java 25

### Type of Server

Vanilla Forge

### Your Expectation

When shifting over anything in NEI that would have thaumcraft aspects it would show correctly. 

### The Reality

It's not... Seems to have broken sometime between 2.8.0 and 2.8.1 and someone said current daily also has this issue. 

Image

### Your Proposal

Bring Back Aspects in NEI <3 

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by slprime**
### Aspect from ItemStack Handler
image

### Alignment the handlers
| before | after |
|-|-|
|image|image|
|image|image|
|image|image|
|image|image|

### Other
1. Add usege handler for items
2. closed: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/22117

### CODE REVIEW

**Review by tomprince — CHANGES_REQUESTED** [review]
I tested this out, and it appears that with this the "Aspect from ItemStack" page in NEI only shows a single box of results (which is often not enough to show all stacks that give the given aspect). Previously, there would multiple boxes of items that have the given aspect.

**Comment by slprime** [comment]
hm... i will check. thx

**Review by boubou19 — DISMISSED** [review]

**Comment by boubou19** [comment]
> does it change with gui scale?

No. Unless you set it high enough then it simply doesn't show the second recipe
image
No bug with second recipe if second recipe doesn't exist i guess

**Comment by slprime** [comment]
fixed: 
image

File: src/main/java/ru/timeconqueror/tcneiadditions/mixins/late/thaumcraft/ClientTickEventsFMLMixin.java [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+            GL11.glDisable(GL11.GL_LIGHTING);
+            GL11.glDisable(GL11.GL_DEPTH_TEST);
+
+            Point mouse = GuiDraw.getMousePosition();
+            int shiftx = -8;
+            int shifty = -8;
+            if (Thaumcraft.instance.aspectShift) {
+                shiftx -= 8;
+                shifty -= 8;
+            }
```
Comment (danyadev) [inline src/main/java/ru/timeconqueror/tcneiadditions/mixins/late/thaumcraft/ClientTickEventsFMLMixin.java]: Without aspectShift it looks much better (with / without)
| shift | no shift |
| - | - |
| Image | Image |

File: src/main/java/ru/timeconqueror/tcneiadditions/nei/AspectFromItemStackHandler.java [hunk 2]
```diff
@@ -55,9 +59,52 @@ public String getRecipeName() {
         return StatCollector.translateToLocal("tcneiadditions.aspect_from_itemstack.title");
     }
 
+    protected AspectList getAspectsForItemStack(ItemStack stack) {
+        final int hash = ScanManager.generateItemHash(stack.getItem(), stack.getItemDamage());
+        final List<String> list = (List) Thaumcraft.proxy.getScannedObjects().get(playerName);
```
Comment (danyadev) [inline src/main/java/ru/timeconqueror/tcneiadditions/nei/AspectFromItemStackHandler.java]: unnecessary `(List)`

**Review by danyadev — CHANGES_REQUESTED** [review]

**Comment by danyadev** [comment]
for some reason on small window size the sensitive area is above the icon
image

File: src/main/java/ru/timeconqueror/tcneiadditions/mixins/late/thaumcraft/ClientTickEventsFMLMixin.java [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+            int ySize = UtilsFX.getGuiYSize(gui);
+            int guiLeft = GuiRecipeHelper.getGuiLeft(guiRecipe);
+            int guiTop = GuiRecipeHelper.getGuiTop(guiRecipe);
+
+            if (mouse.x >= guiLeft && mouse.x <= guiLeft + xSize && mouse.y >= guiTop && mouse.y <= guiTop + ySize) {
+                return;
+            }
+        }
+
+        final int h = ScanManager.generateItemHash(stack.getItem(), stack.getItemDamage());
```
[the remark this answers is not in the document]
Comment (slprime) [reply src/main/java/ru/timeconqueror/tcneiadditions/mixins/late/thaumcraft/ClientTickEventsFMLMixin.java]: fix

File: src/main/java/ru/timeconqueror/tcneiadditions/nei/AspectFromItemStackHandler.java (hunk 2 above)
Comment (slprime) [reply src/main/java/ru/timeconqueror/tcneiadditions/nei/AspectFromItemStackHandler.java]: fix

File: gradle.properties [hunk 4]
```diff
@@ -232,7 +232,10 @@ curseForgeRelations =
 # Whether IDEA should run spotless checks when pressing the Build button.
 # This is meant to be set in $HOME/.gradle/gradle.properties.
 # ideaCheckSpotlessOnBuild = true
+<<<<<<< Updated upstream
 
 # Non-GTNH properties
 org.gradle.configuration-cache = true
 org.gradle.parallel = true
+=======
+>>>>>>> Stashed changes
```
[the remark this answers is not in the document]
Comment (slprime) [reply gradle.properties]: fix

**Review by danyadev — APPROVED** [review]
